### ISSUE TITLE
BUG: Reaction modules fails with math formula in arrow label AND subscript ?

### ISSUE THREAD

**Issue by jakobjakobson13** [cgnieder/chemformula#10]
Dear Clemens,

the following formula works for me only in this form
```latex
\begin{reaction}
  S0 ->[{$h \nu$}] S_{$\geq 1$}
\end{reaction}
```

If I remove the curly brackets in the arrow label, 
```latex
\begin{reaction}
  S0 ->[$h \nu$] S_{$\geq 1$}
\end{reaction}
```
the compilation of the document with `chemforumula v4.15e` and `chemmacros v5.8b` fails. For me this is not an obvious caveat or is it?

Regards

Jakob

**Comment by cgnieder** [comment]
Just remove the blank between `h` and `\nu`:

```latex
\documentclass{article}
\usepackage{chemformula}

\begin{document}

\ch{ S0 ->[$h\nu$] S_{$\geq 1$} }

\end{document}
```
