### ISSUE TITLE
superscripts are vertically shifted with respect to standard text-mode and math-mode superscripts

### ISSUE THREAD

**Issue by tstone-1** [cgnieder/chemformula#15]
(please excuse the preliminal submission of this question, suffered from fat fingers syndrome while still trying to find out what was going on...)

```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{chemformula}

\begin{document}

\(^{1}J\)\ch{^{1}J}\(^{1}\textrm{J}\)\(^{1}\)J\textsuperscript{1}J

\(^{1}J \left( \ch{^{1}H},\ch{^{31}P} \right)\)

\end{document}
```

compiles to give

![Screenshot 2020-09-07 17 02 05](https://user-images.githubusercontent.com/48162401/92400281-fedcea80-f12b-11ea-8c87-de5dbf03e908.png)

As you can see, the superscripts created within `\ch` are printed a little higher in the vertical dimension with regard to text-mode and math-mode superscripts. This looks a bit odd to me in the second line. Is there a way to have those superscripts at the same height? I must me overlooking something in the manual. I couldn't find any option to `\ch` that had visual influence on the height of the numbers. Thank you in advance...!

**Comment by cgnieder** [comment]
I transferred the issue as it really is about the behavior of a chemformula command, `\ch`.

Said command does not use math mode for sub- and superscripts. This is so it can handle the various different situations, horizontal shifts, Kroeger-Vink notation, …

You can adapt the vertical shift to your needs with the options `subscript-vshift` and `charge-vshift`. -0.2ex looks about right:

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{chemformula}
\setchemformula{ charge-vshift = -.2ex }
\begin{document}

\(^{1}J\)\ch{^{1}J}\(^{1}\textrm{J}\)\(^{1}\)J\textsuperscript{1}J

\end{document}
```

![image](https://user-images.githubusercontent.com/2248538/99908790-e15bfd80-2ce4-11eb-8bc5-1d3499b8281c.png)

----

The difference between `article` and `scrartcl` in your example is the default font size which is 10pt for `article` but 10.95pt for `scrartcl`. Also I would argue that using `\left(` and `\right)` here, anyway.

**Comment by tstone-1** [comment]
Thank you for your suggestion. I would like to share an example with the font I'm actually using right now, Minion Pro:

```
\documentclass[fontsize=12pt]{scrartcl}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[lf]{MinionPro}

\usepackage[ngerman]{babel}

\usepackage{lipsum}
\usepackage{chemformula}

\begin{document}

\lipsum[1][1] Es wird erwartungsgemäß eine große \(^{1}J\)(\ch{^{31}P},\ch{^{1}H})-Kopplungskonstante beobachtet. Das \ch{Ag+}-Ion ist ein schönes Ion. \lipsum[1][1]

\lipsum[1][1] Es wird erwartungsgemäß eine große \(^{1}J\left(\ch{^{31}P},\ch{^{1}H}\right)\)-Kopplungskonstante beobachtet. Das \ch{Ag+}-Ion ist ein schönes Ion. \lipsum[1][1]

\setchemformula{ charge-vshift = -.25ex }

\lipsum[1][1] Es wird erwartungsgemäß eine große \(^{1}J\)(\ch{^{31}P},\ch{^{1}H})-Kopplungskonstante beobachtet. Das \ch{Ag+}-Ion ist ein schönes Ion. \lipsum[1][1]

\setchemformula{ charge-vshift = 0ex }

\lipsum[1][1] Es wird erwartungsgemäß eine große \(^{1}J\)(\textsuperscript{31}P,\textsuperscript{1}H)-Kopplungskonstante beobachtet. Das \ch{Ag+}-Ion ist ein schönes Ion. \lipsum[1][1]

\end{document}
```

will give:

![Screenshot 2020-12-15 11 04 22](https://user-images.githubusercontent.com/48162401/102200619-5fb35600-3ec5-11eb-9697-335a901eded8.png)

In the first paragraph, the mass numbers are vertically shifted to such an extent that I wanted the braces to be somewhat more enclosing. However, the second paragraph (which uses `\left(` and `\right)`) looks unpleasant as well - which is why you discourage the use of those braces, I guess? Within the third paragraph, things look quite balanced for the coupling constant. However, as `charge-vshift` was adjusted, the plus symbol for the silver cation is also moved downwards. Looks quite unaesthetic to me... I currently tend to go for the solution as shown in the fourth paragraph where the _J_ coupling is not using `\ch`. I'm very interested in your thoughts on this!

**Comment by cgnieder** [comment]
Personally I would only ever use `\left` and `\right` in display math environments where I have mathematical expressions which actually require larger parentheses. I would _never_ use them in text mode because a) the do not need to extend whats inside of them to make their usage clear and b) they distort the line height when they extend `\baselineskip` which is exactly what you are experiencing. IMHO this is quite independent from the case at hand…

Personally I would go with the third option, possibly also fiddling wit the option `plus-output-symbol`…

**Comment by tstone-1** [comment]
Well, I guess that `plus-output-symbol` only affects the superscript within `\ch{Ag+}` and not influences something like `\ch{SO4^{2-}}` in the same manner, so more adjustments might be necessary? Also, math mode seems to introduce some spacing after comma, presumably something like `\,`. I like the visual appearance of the fifth paragraph:

```
\documentclass[fontsize=12pt]{scrartcl}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[lf]{MinionPro}

\usepackage[ngerman]{babel}

\usepackage{lipsum}
\usepackage{chemformula}

\begin{document}

\lipsum[1][1] Es wird erwartungsgemäß eine große \(^{1}J\)(\ch{^{31}P},\ch{^{1}H})-Kopplungskonstante beobachtet. Das \ch{Ag+}-Ion ist ein schönes Ion. \lipsum[1][1]

\lipsum[1][1] Es wird erwartungsgemäß eine große \(^{1}J\left(\ch{^{31}P},\ch{^{1}H}\right)\)-Kopplungskonstante beobachtet. Das \ch{Ag+}-Ion ist ein schönes Ion. \lipsum[1][1]

\setchemformula{ charge-vshift = -.25ex }

\lipsum[1][1] Es wird erwartungsgemäß eine große \(^{1}J\)(\ch{^{31}P},\ch{^{1}H})-Kopplungskonstante beobachtet. Das \ch{Ag+}-Ion ist ein schönes Ion. \lipsum[1][1]

\setchemformula{ charge-vshift = 0ex }

\lipsum[1][1] Es wird erwartungsgemäß eine große \(^{1}J\)(\textsuperscript{31}P,\textsuperscript{1}H)-Kopplungskonstante beobachtet. Das \ch{Ag+}-Ion ist ein schönes Ion. \lipsum[1][1]

\lipsum[1][1] Es wird erwartungsgemäß eine große \(^{1}J\)(\textsuperscript{31}P,\,\textsuperscript{1}H)-Kopplungskonstante beobachtet. Das \ch{Ag+}-Ion ist ein schönes Ion. \lipsum[1][1]

\end{document}
```

![Screenshot 2020-12-20 17 28 48](https://user-images.githubusercontent.com/48162401/102718548-01cda680-42e9-11eb-962f-8e87e36af52a.png)

**Comment by cgnieder** [comment]
Actually, `plus-output-symbol` does nothing because the option doesn't exist any more. May bad. IIRC it didn't effect charges anyway.

You're right about commas and math mode, of course, but this is a well known TeX fact:

```
$(x,y)$ vs. ($x$,$y$) vs. $(x{,}y)$
\bye
```
![image](https://user-images.githubusercontent.com/2248538/102718826-adc3c180-42ea-11eb-879c-736851947c74.png)

See for example https://tex.stackexchange.com/questions/303110/ for one of many questions on this topic.

I'm not sure I'm of much help here… I already told you my opinion and my preference. The choice is up to you in the end.

**Comment by cgnieder** [comment]
I decided to add an option `math-scripts` which actually will use the nativ math mechanism to create the sub- and superscripts (which will however disable the `vshift` options):

```latex
\documentclass{article}
\usepackage{chemformula}

\begin{document}

$^1J$\ch{^1J} $A_2$\ch{A2}  $B_2^2$\ch{B2^2}

\setchemformula{ math-scripts = true }

$^1J$\ch{^1J} $A_2$\ch{A2} $B_2^2$\ch{B2^2}

\end{document}
```

![image](https://user-images.githubusercontent.com/2248538/102823154-a4b21d80-43da-11eb-8ac1-533cedf3fe54.png)

**Comment by cgnieder** [comment]
I just pushed the new version to CTAN and will close this issue now.
