### ISSUE TITLE
Starred version of \isotope doesn't work inside \ch

### ISSUE THREAD

**Issue by rafaelpap** [cgnieder/chemformula#16]
Dear Sir,
if I use `\isotope*{element}` inside `\ch` it shows the following error message at compilation time:

```
! Missing number, treated as zero.
<to be read again> 
                   \@elements@atom@name@num@\chemformula_star_adduct:  
l.19 \item The \ch{\isotope*{Cl}}
                                  is the most abundant.
```

The text file used is:

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{kpfonts}
\usepackage{chemgreek}
\usepackage[utf8]{inputenc}
\usepackage{chemformula}
\usepackage{chemmacros}
\usechemmodule{isotopes}

\begin{document}

\begin{itemize}
\item The \isotope{Cl} is the most abundant.
\item The \isotope*{Cl} is the most abundant.
\end{itemize}

\begin{itemize}
\item The \ch{\isotope{Cl}} is the most abundant.
\item The \ch{\isotope*{Cl}} is the most abundant.
\end{itemize}

\end{document}
```

with pdflatex it produces the attached pdf

[isotope.pdf](https://github.com/cgnieder/chemmacros/files/5977664/isotope.pdf)

I am using 

Package: chemmacros 2020/11/21 v5.11a comprehensive support for typesetting chemistry documents (CN)
File: chemmacros.module.isotopes.code.tex 2020/11/21 v5.11a chemmacros module `
isotopes' 2015/07/22 a macro to easily print element isotopes

Thanks for the attention,
Rafael

**Comment by cgnieder** [comment]
The reason is clear – the star is a special input type for `chemformula`:

```latex
\documentclass{article}
\usepackage{chemformula}
\begin{document}
\ch{Na2SO4 * 10 H2O}
\end{document}
```
![image](https://user-images.githubusercontent.com/2248538/107878741-e93ad080-6ed4-11eb-9d2d-030b73c4017a.png)

The standard way out is of course escaping:

```latex
\documentclass{article}
\usepackage{chemmacros}
\chemsetup{formula=chemformula}
\begin{document}
\ch{"\isotope*{Cl}"}
\end{document}
```

Another possibility is disabling the special input `*`:

```latex
\documentclass{article}
\usepackage{chemmacros}
\chemsetup{formula=chemformula}
\RemoveChemCompoundProperty{*}
\begin{document}
\ch{\isotope*{Cl}}
\end{document}
```

**Comment by rafaelpap** [comment]
I am sorry to bother you again. I am unable to use the escaped version when the formula is like:
\ch{"\isotope*{H}"2}
the error message is:

! Missing number, treated as zero.
<to be read again> 
                   \@elements@atom@name@num@\chemformula_star_adduct:  
l.6 \ch{"\isotope*{Cl}"2}

I am using:

\documentclass{article}
\usepackage{chemmacros}
\usechemmodule{isotopes}
\chemsetup{formula=chemformula}
\begin{document}
\ch{"\isotope*{Cl}"2}
\end{document}

Thanks,
Rafael
