### ISSUE TITLE
Allow multiple lines above and below arrows

### ISSUE THREAD

**Issue by bradrn** [cgnieder/chemformula#17]
Currently text above and below arrows is typeset as an hbox:

https://github.com/cgnieder/chemformula/blob/f709324af5e396d1babd641b84a7d9eccc654f0a/chemformula.sty#L893-L896

This means that each box can contain only one line of text. However, now and then I wish to to typeset multiple lines in these positions (e.g. for a list of reaction conditions). It would be useful to change this part of the package to allow for this possibility.

**Comment by cgnieder** [comment]
The next release will support the following syntax:

```latex
\documentclass{article}
\usepackage{chemformula}

\begin{document}

\ch{A ->[{A\\B}][ C2D \newline Text ] B}

\end{document}
```
![image](https://user-images.githubusercontent.com/2248538/150638084-b1df0382-410e-42a0-b0b6-625fdb8b5849.png)

**Comment by bradrn** [comment]
Thanks @cgnieder!
