### ISSUE TITLE
it seems doesn't support to display math equation above the arrow

### ISSUE THREAD

**Issue by zousiyu1995** [cgnieder/chemformula#20]
As shown in below, the '$k_1$' is a kinetics constant, it is expected to display as a math style. But, only 'k' is math style, '_1' doesn't display correctly.
![image](https://user-images.githubusercontent.com/7608449/222352152-2b314996-b942-46ea-b1f2-61e122694b99.png)

**Comment by ajhzhsendjx** [comment]
Put space in square brackets -----> ... [ $k_1$ ] ...

**Comment by zousiyu1995** [comment]
> Put space in square brackets -----> ... [ k1 ] ...

Thanks! It solved my problem. But this syntax is wired.
