### ISSUE TITLE
<options> in documentation: not clear to which commands they belong

### ISSUE THREAD

**Issue by Tchiller** [cgnieder/chemformula#4]
Dear Mr. Niederberger,

it would be nice if the options in your documentation would be ordered a bit to the corresponding commands they can be used with. Or are all options usable in any place? You are mentioning options all over the place but just in rare cases you define their scope of usage. 

I try to name all appearances:

`\setchemformula{<options>} `on page 3 (and the two commands from chemmacros (all appearing a second time on page 4)

`\ch[<options>]{<input>}` on page 3

`\chcpd[<options>]{<compound>} `on page 18

`font-spec={[<options>]<font>} `on page 33 (I guess, this "options" has nothing to do with the rest)

`\chlewis[<options>]{<electron spec>}{<atom>}` on page 35

On information on where to put all those options you have:
"There are some options to customize the output of the \ch command. They can either be
applied locally using the optional argument or can be set globally using the setup command." on page 4

"Enable the Kröger-Vink notation. As most options this can be enabled globally via the setup command or locally as option to \ch." on page 37

---

It would be nice if you could clarify where to use what. Right now, you do never mention `\chcpd` regarding any options. What about `tikz-external-disable`? Only for global? What about the Lewis options, only for global and `\chlewis`? 

Right now I see 5 occurrences of `<options>` in the documentation. I think you are the person which does know best which options makes sense (and work) on which commands. I could try them all, but maybe you already have some lists on this. 

The reason I am asking: I am writing a .cwl file (http://tex.stackexchange.com/a/263504) for this package. As it stands now, the user of TeXstudio gets a huge amount of options offered when using `\setchemformula` which is really nice. But it would be even nicer if I can teach the user, where to use which option by offering him the right choices. 

Thanks and feel free to ask, if this was not understandable.

**Comment by cgnieder** [comment]
All of chemformula's options are equal: they can be set with any of the possibilities you mention (except those in the `fontspec` key: they are used as argument to `fontspec`'s `\newfontfamily`…)

The sentence “As most options […]” is probably misleading. Of course not all options do make sense locally: `circletype` or `decimal-marker` (just to give some examples) probably shsould be set globally in the preamble as they define some general layout. Something like `arrow-ratio` however might make sense both globally (for general layout) and locally (for indicating different equilibria).

**Comment by cgnieder** [comment]
It is hard to give a general advice. Even something like `tikz-external-disable` could make more sense locally (inside a TikZ picture) but still be set with `\setchemformula` (which sets options always local to the scope it is used in).
