### ISSUE TITLE
Strange variant for prop_if_in

### ISSUE THREAD

**Issue by blefloch** [cgnieder/chemformula#5]
I'm refining the error detection of `\cs_generate_variant:Nn` and it now complained about the following line in `chemformula.sty`:

```
\cs_generate_variant:Nn \prop_if_in:NnT { x }
```

turning `N`-type argument into `x`-type is not really supported, as the result of an `x`-expansion has no reason to be a single-token.  Since you don't seem to be using that variant (perhaps a typo for `Nx`?) I would appreciate if you could remove it, as I could then push my `expl3` changes without fear of breaking documents in the wild.

**Comment by cgnieder** [comment]
Sorry it took me so long to respond. I fixed this in the source file and will make an update in the next few days. Thanks.
