### ISSUE TITLE
Feature Request: squiggly arrows

### ISSUE THREAD

**Issue by gldraper** [cgnieder/chemformula#6]
Hi,

I've just started using this package and so far it's fantastic. Have you ever considered adding squiggly arrows to your package for all the photo/radiation chemists out there? Something like \rightsquigarrow from the package amssymb. 

If you made this addition, I would be a very happy PhD student!

Thanks

**Comment by cgnieder** [comment]
You can already add any arrows you need yourself:

```latex

\documentclass{article}
\usepackage{chemformula}
\usetikzlibrary{decorations.pathmorphing}

\NewChemArrow{w>}{
  \draw[decorate,decoration={coil,aspect=0,segment length=4pt,post length=2pt},chemarrow,-cf]
  (cf_arrow_start) -- (cf_arrow_end) ;
}

\begin{document}

\ch{A w> B}

\end{document}
```

**Comment by gldraper** [comment]
Thank you very much for this!
