### ISSUE TITLE
Feature request: Support for *mathtools* `\shortintertext` in the reactions environment

### ISSUE THREAD

**Issue by tmgriffiths** [cgnieder/chemformula#7]
This is a feature request stemming from [this stackexchange question](http://tex.stackexchange.com/q/358037/54688). Essentially, I'd like to be able to use `\shortintertext` from the `mathtools` package inside the reaction environment. The main difference (visually anyway) between `\shortintertext` and `\intertext` is the vertical spacing around the output. 

**`\intertext`**
[intertext.pdf](https://github.com/cgnieder/chemformula/files/836439/intertext.pdf)

**`\shortintertext`**
[shortintertext.pdf](https://github.com/cgnieder/chemformula/files/836436/shortintertext.pdf)

`\shortintertext` works inside the align environment from `amsmath`, which the reactions environment is based on, but is currently unsupported by `chemmacros`.

**Comment by cgnieder** [comment]
Thanks. I haven't forgotten about this one but didn't find the time, yet…
